### PR TITLE
Merge dev branch into main

### PR DESCRIPTION
**Pull request by Xskullibur**
### Database Schema Updates

- Added a new column email_verified to the users table.
- Updated insertion scripts to include email_verified.

#### Dependencies

- Added httpclient5 for testing purposes.
- Updated the scope of h2 dependency from test to runtime.
- Added jackson-datatype-jsr310 dependency.

#### Authentication and User Management

- Refactored AdminService to include email service for sending temporary passwords.
- Introduced AuthServiceImpl and PasswordGeneratorServiceImpl with updated logic for handling authentication and password generation.
- Implemented email verification functionality in AuthenticationController.
- Added endpoints for sending verification emails and verifying email tokens.
- Updated JWT service to handle email verification tokens.

### Notes
- Please review the changes in the authentication logic carefully as they affect multiple parts of the application.

### CODE REVIEW

**Comment by Xskullibur** [comment]
> ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=G1-T3_g1-t3&pullRequest=22) **Quality Gate failed**
> Failed conditions  [1 Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=G1-T3_g1-t3&pullRequest=22&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true)  [7.7% Duplication on New Code](https://sonarcloud.io/component_measures?id=G1-T3_g1-t3&pullRequest=22&metric=new_duplicated_lines_density&view=list) (required ≤ 3%)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=G1-T3_g1-t3&pullRequest=22)

Ignoring the code duplication condition as it is necessary for the current implementation. The duplicated code is essential to maintain the functionality and integrity of the application.

**Comment by ceewaigit** [comment]
Geolocation permissions check - safe.

**Comment by saracyh** [comment]
SecurityConfig.java: 
1. CSRF Protection: You've disabled CSRF protection (http.csrf(csrf -> csrf.disable()), which can expose the application to cross-site request forgery attacks. Please reconsider enabling CSRF protection unless there's a specific reason to keep it off.
2. CORS Configuration: The current CORS setup allows all headers and credentials from http://localhost:3000. Ensure this configuration is appropriate for production environments and restrict origins and headers to only what is necessary.
3. Endpoint Access: Multiple endpoints are publicly accessible:
/authentication/**
/leaderboard/**
/profile/**
/tournament/**
/ws/**
GET /matches/current/** Ensure these endpoints are secure and do not expose sensitive information. Consider adding more granular security controls where necessary.
4. Logging: Make sure sensitive information (e.g., passwords, tokens) is not logged. Logging should be reviewed to avoid exposing critical data.
5. Session Management: You’ve set the session creation policy to stateless (SessionCreationPolicy.STATELESS), which impacts session management. Confirm this is the desired behavior for your use case.
6. Custom Filters: The JwtAuthenticationFilter is placed before UsernamePasswordAuthenticationFilter. Ensure that the custom filter is secure and does not introduce vulnerabilities.
7. Error Handling: Review exception handling to ensure that detailed error messages or stack traces are not exposed to end-users, as this could provide attackers with useful information.

AuthService.java:
1. Exception Handling: Improve exception handling in validateToken to avoid exposing stack traces or detailed error messages.
2. Token Validation: Ensure robust validation of the JWT token format and structure.

JwtAuthenticationFilter.java:
1. Error Handling: Use more granular error handling to prevent exposing sensitive information.
2. Filter Logic: Optimize the filtering logic to reduce overhead and potential security gaps.

AuthenticationController.java:
1. Input Validation: Validate the input token thoroughly before processing.
2. Response Handling: Ensure responses do not expose sensitive information about the authentication process.

**Comment by Xskullibur** [comment]
> SecurityConfig.java:
> 
> 1. CSRF Protection: You've disabled CSRF protection (http.csrf(csrf -> csrf.disable()), which can expose the application to cross-site request forgery attacks. Please reconsider enabling CSRF protection unless there's a specific reason to keep it off.
> 2. CORS Configuration: The current CORS setup allows all headers and credentials from http://localhost:3000. Ensure this configuration is appropriate for production environments and restrict origins and headers to only what is necessary.
> 3. Endpoint Access: Multiple endpoints are publicly accessible:
>    /authentication/**
>    /leaderboard/**
>    /profile/**
>    /tournament/**
>    /ws/**
>    GET /matches/current/** Ensure these endpoints are secure and do not expose sensitive information. Consider adding more granular security controls where necessary.
> 4. Logging: Make sure sensitive information (e.g., passwords, tokens) is not logged. Logging should be reviewed to avoid exposing critical data.
> 5. Session Management: You’ve set the session creation policy to stateless (SessionCreationPolicy.STATELESS), which impacts session management. Confirm this is the desired behavior for your use case.
> 6. Custom Filters: The JwtAuthenticationFilter is placed before UsernamePasswordAuthenticationFilter. Ensure that the custom filter is secure and does not introduce vulnerabilities.
> 7. Error Handling: Review exception handling to ensure that detailed error messages or stack traces are not exposed to end-users, as this could provide attackers with useful information.
> 
> AuthService.java:
> 
> 1. Exception Handling: Improve exception handling in validateToken to avoid exposing stack traces or detailed error messages.
> 2. Token Validation: Ensure robust validation of the JWT token format and structure.
> 
> JwtAuthenticationFilter.java:
> 
> 1. Error Handling: Use more granular error handling to prevent exposing sensitive information.
> 2. Filter Logic: Optimize the filtering logic to reduce overhead and potential security gaps.
> 
> AuthenticationController.java:
> 
> 1. Input Validation: Validate the input token thoroughly before processing.
> 2. Response Handling: Ensure responses do not expose sensitive information about the authentication process.

SecurityConfig.java:

1. CSRF protection was disabled as we are using JWT tokens to authenticate, since they are stateless by nature CSRF protection is not necessary
2. Updated CORS configuration to only allow Authorization and Content-Type as headers. Origins will be updated when the domain is retrieved
3. Updated endpoints, websockets endpoint security will be updated in the next sprint
4. No logging of sensitive information
5. Can confirm Session Management policy behaviour
6. Updated filters

The rest looks good to me

**Pull request merged**
